---
- name: Playbook para desplegar Plesk
  hosts: localhost
  become: yes
  vars:
    plesk_email: "mbut182@g.educaand.es"
    plesk_password: "admin"
    php_modules:
      - php7.4-mysql
      - php7.4-curl
      - php7.4-gd
      - php7.4-intl
      - php7.4-imap
      - php7.4-xml
      - php7.4-mbstring
      - php7.4-zip
  tasks:
    - name: Actualizar los paquetes
      apt:
        update_cache: yes

    - name: Instalar wget
      apt:
        name: wget
        state: present

    - name: Descargar el instalador de Plesk
      get_url:
        url: https://installer.plesk.com/plesk-installer
        dest: /tmp/plesk-installer
        mode: 'a+x'

    - name: Instalar Plesk
      command: sudo ./tmp/plesk-installer

    - name: Instalar módulos de PHP
      apt:
        name: "{{ php_modules }}"
        state: present

    - name: Instalar Postfix
      apt:
        name: postfix
        state: present

    # - name: Configurar Plesk
    #   shell: |
    #     plesk bin settings --set panel_ini_components=all
    #     plesk bin poweruser --off
    #     plesk bin mail --off
    #     plesk bin autoresponder --off
    #     plesk bin spamassassin --off
    #     plesk bin antivirus --off
    #     plesk bin mail_auth_view --off
    #     plesk bin dns --off
    #     plesk bin smarthost --off
    #     plesk bin mchk --with-spam
    #     plesk bin extension --install-url https://ext.plesk.com/packages/c4abeef6-16a6-4a08-bc12-c68a4dee4139-panel-landing-page/download --force
