---
- name: Playbook install load balancer
  hosts: balancer
  become: yes

  vars_files:
    - ../software/vars/variables.yml

  tasks:

    - name: Actualizar los paquetes
      apt:
        update_cache: yes

    - name: Instalamos Apache
      apt:
        name: apache2
        state: present

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: proxy

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: proxy_http

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: proxy_ajp

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: rewrite
    
    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: deflate

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: headers

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: proxy_connect

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: proxy_html

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: proxy_balancer

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: lbmethod_bybusyness

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: lbmethod_byrequests

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: lbmethod_bytraffic

    - name: Activamos los módulos necesarios
      apache2_module:
        state: present
        name: lbmethod_heartbeat

    - name: Copiamos el archivo de configuración de Apache
      copy:
        src: /home/ubuntu/Proyecto-ASIR/infraestructura/conf/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        remote_src: yes
        mode: '0644'

    - name: Reemplazamos las variables del archivo de configuración
      replace:  
        path: /etc/apache2/sites-available/000-default.conf
        regexp: 'IP_HTTP_SERVER_1'
        replace: '{{ ip_http_server_1 }}'

    - name: Reemplazamos las variables del archivo de configuración
      replace:  
        path: /etc/apache2/sites-available/000-default.conf
        regexp: 'IP_HTTP_SERVER_2'
        replace: '{{ ip_http_server_2 }}'

    - name: Reiniciamos el servidor Apache
      service: 
        name: apache2
        state: restarted